### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by elukaweski** [forcedotcom/maven-force-plugin#1]
I am testing out this plugin and can't seem to get it working. I am getting the following error:

Embedded error: Illegal prefix for connection url ("force://login.salesforce.com;user=a@b.com;password=passwordxxxxxxxV6ZWtAFW6o9p2FIc"). 
It must start with force://

I built using 22.0.5-BETA of the architype and so believe that I am using the 22.0.5-BETA version of the SDK.

Anything else I should look for?

Thanks

**Comment by jsimone** [comment]
Can you post the plugin element for the maven-force-plugin and configuration from your pom?

**Comment by elukaweski** [comment]
Thanks for the response. The pom element is (sorry about the formatting...still learning this markdown stuff:

&lt;plugin>
            &lt;groupId>com.force&lt;/groupId>
            &lt;artifactId>maven-force-plugin&lt;/artifactId>
            &lt;version>22.0.5-BETA&lt;/version>
            &lt;executions>
                &lt;execution>
                    &lt;id>generate-force-entities&lt;/id>
                    &lt;goals>
                        &lt;goal>codegen&lt;/goal>
                    &lt;/goals>
                &lt;/execution>
            &lt;/executions>
            &lt;configuration>
                &lt;all>true&lt;/all>
                &lt;connectionName>connName&lt;/connectionName>
                &lt;destDir>${basedir}/src/main/java&lt;/destDir>
                &lt;packageName>com.serjann.gencode.name&lt;/packageName>
            &lt;/configuration>
        &lt;/plugin>

**Comment by elukaweski** [comment]
ok...let's try that again

**Comment by tkral** [comment]
I believe the issue is that the double quote is coming in with the URL. So it's unable to properly match the URL prefix.

**Comment by elukaweski** [comment]
aha...thanks....one of those things with windows and it's SET command. Let me play with that.
Thanks, again...will let you know

**Comment by elukaweski** [comment]
ok...that did it....what a newbie error :)

**Comment by tkral** [comment]
I'm glad that fixed your issue :).  What was the specific problem with Windows SET?  How did you fix it?  If you could let us know, it would be a huge help.  Thanks!

**Comment by elukaweski** [comment]
sure....my set command looked like this:
set FORCE_CONNNAME_URL="force://login.salesforce.com;user=a@b.com;password=passwordxxxxxxxV6ZWtAFW6o9p2FIc"

And, as you mentioned, the quote marks became a part of the environment variable. Deleting the quote marks solved the problem.

As a point of interest, this resulted from originally trying to use the current URL format, as in

set FORCE_CONNNAME_URL="force://login.salesforce.com?user=a@b.com&amp;password=passwordxxxxxxxV6ZWtAFW6o9p2FIc"

where I was encoding the &. as "&amp;" ...windows cmd was objecting to that encoding which caused me to put in the quote marks...but, I never did follow that path and try to solve it since I reverted to the older URL format
